name: create-release
on:
  push:
    tags:
      - v*
permissions:
  contents: read
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          args: --current --strip all
        env:
          OUTPUT: /tmp/release-notes.md
      - run: sudo apt-get install libwayland-dev meson wayland-protocols
      - run: meson setup --buildtype release build
      - run: git diff main
      - run: meson dist -C build
      - uses: softprops/action-gh-release@v2
        with:
          body_path: /tmp/release-notes.md
          files: |
            build/meson-dist/still-${{ steps.git-cliff.outputs.version }}.tar.xz
            build/meson-dist/still-${{ steps.git-cliff.outputs.version }}.tar.xz.sha256sum
          token: ${{ steps.app-token.outputs.token }}
