name: push
on:
  push:
    branches:
      - '**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
permissions:
  contents: read
jobs:
  build:
    name: build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: sudo apt-get install libpixman-1-dev libwayland-dev meson scdoc wayland-protocols
      - run: meson setup --buildtype release build
      - run: ninja -C build test
      - run: ninja -C build
  bump-version:
    if: github.ref_name == github.event.repository.default_branch
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
      - uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          args: --bump
        env:
          OUTPUT: CHANGELOG.md
      - name: bump version
        env:
          version: ${{ steps.git-cliff.outputs.version }}
        run: |
          sed -i -e "s/^\(\s\+version\): '.*'/\1: '${version#v}'/" meson.build
          git add CHANGELOG.md meson.build

          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          if git commit -m "chore: $version"; then
            git push origin

            git tag "$version"
            git push origin --tags
          fi
