name: push
on:
  push:
    branches:
      - '**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
permissions:
  contents: read
jobs:
  build:
    name: build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: sudo apt-get install libwayland-dev meson wayland-protocols
      - run: meson setup --buildtype release build
      - run: ninja -C build
